name: bloop
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  curved_navigation_bar: ^0.3.2
  fluttertoast: ^4.0.0
  flutter:
    sdk: flutter

  
  cupertino_icons: ^0.1.2
  simple_animations: ^1.3.3
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+3
  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^1.4.1
  provider: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/logo.png 
    - assets/logohemo.png

  fonts:
     - family: CaviarDreams
       fonts:
          - asset: fonts/CaviarDreams_Bold.ttf
          - asset: assets/fonts/sf-ui-display-light.otf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
